const styles = {
  container: {
    display: "flex",
    height: "100vh",
    fontFamily: "'Segoe UI', sans-serif",
    color: "#333",
  },
  sidebar: {
    width: "250px",
    backgroundColor: "#111827",
    color: "#fff",
    display: "flex",
    flexDirection: "column",
    padding: "20px 15px",
    boxShadow: "2px 0 10px rgba(0,0,0,0.1)",
  },
  navButton: (active) => ({
    backgroundColor: active ? "#4f46e5" : "transparent",
    color: active ? "#fff" : "#d1d5db",
    border: "none",
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "12px 16px",
    textAlign: "left",
    marginBottom: "12px",
    borderRadius: "8px",
    fontWeight: "500",
    cursor: "pointer",
    transition: "all 0.2s ease-in-out",
  }),
  main: {
    flexGrow: 1,
    backgroundColor: "#f3f4f6",
    padding: "40px",
    overflowY: "auto",
  },
  section: {
    background: "#fff",
    padding: "30px",
    borderRadius: "12px",
    boxShadow: "0 0 10px rgba(0,0,0,0.05)",
    maxWidth: "700px",
    margin: "0 auto",
    transition: "all 0.3s ease",
  },
  header: {
    fontSize: "24px",
    fontWeight: "bold",
    marginBottom: "20px",
    color: "#111827",
  },
  input: {
    width: "100%",
    padding: "10px",
    marginBottom: "15px",
    borderRadius: "8px",
    border: "1px solid #cbd5e1",
    fontSize: "16px",
  },
  button: {
    backgroundColor: "#4f46e5",
    color: "#fff",
    padding: "10px 20px",
    borderRadius: "8px",
    border: "none",
    fontWeight: "bold",
    cursor: "pointer",
    marginTop: "10px",
    transition: "transform 0.2s",
  },
};

export default styles;
